CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main_stage2.py \
        --train_dir "/home/sdb1/datasets/imagenet/train" \
        --val_dir "/home/sdb1/datasets/imagenet/val" \
        --log_dir "logs/stage2" \
        --arch swin \
        --dist-url 'tcp://127.0.0.1:10001' \
        --dist-backend 'nccl' \
        --world-size 1 \
        --rank 0 \
        --batch-size 64 \
        --lr 0.001 \
        --lr_inner 0.001 \
        --epochs 50 \
        --coeff_inner 1 \
        --wd 1e-1 \
        --print-freq 50 \
        --num_accumulation_steps 2 \
        --pretrained "pretrained/stage1_imagenet.pth.tar" 
